In [1]:
# 1. Nested list comprehension

#matrix = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
m = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
t = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

for i in range(len(m)):
		for j in range(len(m[0])):
			t[j][i] = m[i][j] # = matrix[i][j]

print (t)

[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]


In [2]:
# 2. zip method
m = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
t_m = zip(*m)
for row in t_m:
	print(row)

(1, 4, 7, 10)
(2, 5, 8, 11)
(3, 6, 9, 12)


In [4]:
# 3. numpy method
import numpy as np 
m = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
t_m = np.transpose(m)
print(t_m)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
